version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Logging into AWS'
      - aws --version
      - REPOSITORY_URI=416592256572.dkr.ecr.us-east-1.amazonaws.com
#      - $(aws ecr get-login --region us-east-2 --registry-ids 732631625641)
#      - $(aws ecr get-login-password --region us-east-2)
#      - aws ecr get-authorization-token  --region us-east-2 | sed 's|https://||'
#      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 416592256572.dkr.ecr.us-east-1.amazonaws.com
#      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 416592256572.dkr.ecr.the-region-you-are-in.amazonaws.com
#      - echo 'Logged in successfully'
#      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo 'pre build phase ends here'

  build:
    commands:
      - echo 'build commands phase starting'
      - cd daytrader-example-accountsrepo-master/daytrader-accountsapp
      - mvn install -DskipTests
      - cd daytrader-accounts
#      - docker build . -t $REPOSITORY_URI/daytrader:daytrader-accounts
      - docker build -f Dockerfile -t kakaushi/daytrader-accounts:4.0.18 --build-arg APP_ARTIFACTID=daytrader-accountsapp --build-arg WAR_ARTIFACTID=daytrader-accounts --build-arg APP_VERSION=4.0.0 --build-arg EXPOSE_PORT=1443 --build-arg DATABASE_DRIVER=com.mysql.jdbc.Driver --build-arg DATABASE_URL=jdbc:mysql://tradesdb.c5ntr5qnxgp6.us-east-1.rds.amazonaws.com:3306/tradesdb --build-arg DATABASE_USERNAME=admin --build-arg DATABASE_PASSWORD=Oracle123 .
#      - docker push 416592256572.dkr.ecr.us-east-1.amazonaws.com/daytrader:daytrader-accounts
      - cd ..
      - cd ..
      - cd ..
      - cd daytrader-example-gatewayrepo-master/daytrader-example-gatewayrepo-master/daytrader-gatewayapp
      - mvn install -DskipTests
      - cd daytrader-gateway
#      - docker build . -t $REPOSITORY_URI/daytrader:daytrader-gateway
#      - docker push       $REPOSITORY_URI/daytrader:daytrader-gateway
      - docker build -f Dockerfile -t kakaushi/daytrader-gateway:4.0.18 --build-arg APP_ARTIFACTID=daytrader-gatewayapp --build-arg WAR_ARTIFACTID=daytrader-gateway --build-arg APP_VERSION=4.0.0 --build-arg EXPOSE_PORT=2443 --build-arg DATABASE_DRIVER=com.mysql.jdbc.Driver --build-arg DATABASE_URL=jdbc:mysql://tradesdb.c5ntr5qnxgp6.us-east-1.rds.amazonaws.com:3306/tradesdb --build-arg DATABASE_USERNAME=admin --build-arg DATABASE_PASSWORD=Oracle123 .
      - cd ../../../..
      - cd daytrader-example-portfoliosrepo-master/daytrader-portfoliosapp
      - mvn install -DskipTests
      - cd daytrader-portfolios
#      - docker build . -t $REPOSITORY_URI/daytrader:daytrader-portfolios
#      - docker push       $REPOSITORY_URI/daytrader:daytrader-portfolios
      - docker build -f Dockerfile -t kakaushi/daytrader-portfolios:4.0.18 --build-arg APP_ARTIFACTID=daytrader-portfoliosapp --build-arg WAR_ARTIFACTID=daytrader-portfolios --build-arg APP_VERSION=4.0.0 --build-arg EXPOSE_PORT=3443 --build-arg DATABASE_DRIVER=com.mysql.jdbc.Driver --build-arg DATABASE_URL=jdbc:mysql://tradesdb.c5ntr5qnxgp6.us-east-1.rds.amazonaws.com:3306/tradesdb --build-arg DATABASE_USERNAME=admin --build-arg DATABASE_PASSWORD=Oracle123 .
      - cd ../../..
      - cd daytrader-example-quotesrepo-master/daytrader-example-quotesrepo-master/daytrader-quotesapp
      - mvn install -DskipTests
      - cd daytrader-quotes
#      - docker build . -t $REPOSITORY_URI/daytrader:daytrader-quotes
#      - docker push       $REPOSITORY_URI/daytrader:daytrader-quotes
      - docker build -f Dockerfile -t kakaushi/daytrader-quotes:4.0.18 --build-arg APP_ARTIFACTID=daytrader-quotesapp --build-arg WAR_ARTIFACTID=daytrader-quotes --build-arg APP_VERSION=4.0.0 --build-arg EXPOSE_PORT=4443 --build-arg DATABASE_DRIVER=com.mysql.jdbc.Driver --build-arg DATABASE_URL=jdbc:mysql://tradesdb.c5ntr5qnxgp6.us-east-1.rds.amazonaws.com:3306/tradesdb --build-arg DATABASE_USERNAME=admin --build-arg DATABASE_PASSWORD=Oracle123 .
      - cd ../../../..
      - cd daytrader-example-webrepo-master/daytrader-example-webrepo-master/daytrader-webapp
      - mvn install -DskipTests
      - cd daytrader-web
      - docker build -f Dockerfile -t kakaushi/daytrader-web:4.0.18 --build-arg APP_ARTIFACTID=daytrader-webapp --build-arg WAR_ARTIFACTID=daytrader-web --build-arg APP_VERSION=4.0.0 --build-arg EXPOSE_PORT=5443 --build-arg DATABASE_DRIVER=com.mysql.jdbc.Driver --build-arg DATABASE_URL=jdbc:mysql://tradesdb.c5ntr5qnxgp6.us-east-1.rds.amazonaws.com:3306/tradesdb --build-arg DATABASE_USERNAME=admin --build-arg DATABASE_PASSWORD=Oracle123 .
#      - docker build . -t $REPOSITORY_URI/daytrader:daytrader-web
#      - docker push       $REPOSITORY_URI/daytrader:daytrader-web
      - 

#      - cd ..
#      - aws s3 cp kubernetes-manifests/account-depl.yaml         s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/account-service.yaml      s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/customer-depl.yaml        s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/customer-service.yaml     s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/derby-db-depl.yaml        s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/derby-db-service.yaml     s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/loan-depl.yaml            s3://ss-poc-shibu/
#      - aws s3 cp kubernetes-manifests/loan-service.yaml         s3://ss-poc-shibu/
